#!/usr/bin/env bash
# Regenerates seed.sql from seed.manifest (paths relative to this directory).
# Requires: bash, grep, sed. Run from repo root: pnpm supabase:combine-seeds
set -euo pipefail

SUPABASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MANIFEST="${SUPABASE_DIR}/seed.manifest"
OUT="${SUPABASE_DIR}/seed.sql"

if [[ ! -f "$MANIFEST" ]]; then
  echo "ERROR: Missing ${MANIFEST}"
  exit 1
fi

write_header() {
  cat <<'EOF'
-- ==============================================================================
-- LenserFight Community Edition — Seed Data
-- Contains only OSS-safe schemas: lensers, lenses, content, media, agents, ai,
-- execution, tenancy. Private schemas (battles, billing, xp, analytics, etc.)
-- are excluded.
-- ==============================================================================
-- AUTO-GENERATED by supabase/combine-seeds.sh — edit seed.manifest and seeds/*.sql
-- NOTE: Supabase applies this file via Postgres (not psql), so content is INLINED.
--       Do not use \\ir here; the combine script concatenates each seed file.
-- ==============================================================================

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', 'public, extensions', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

EOF
}

append_manifest_sql() {
  while IFS= read -r line || [[ -n "${line}" ]]; do
    line="${line#"${line%%[![:space:]]*}"}"
    line="${line%"${line##*[![:space:]]}"}"
    [[ -z "$line" ]] && continue
    [[ "$line" == \#* ]] && continue
    line="${line%%#*}"
    line="${line#"${line%%[![:space:]]*}"}"
    line="${line%"${line##*[![:space:]]}"}"
    [[ -z "$line" ]] && continue

    rel_path="$line"
    target="${SUPABASE_DIR}/${rel_path}"
    if [[ ! -f "$target" ]]; then
      echo "ERROR: Manifest entry not found: ${rel_path}"
      exit 1
    fi
    {
      echo ""
      echo "-- >>> ${rel_path}"
      cat "$target"
      echo ""
    } >>"$OUT"
  done < "$MANIFEST"
}

write_header >"$OUT"
append_manifest_sql

# Ensure every top-level seeds/*.sql is listed (Community Edition has no seeds/private)
missing=0
shopt -s nullglob
for f in "${SUPABASE_DIR}"/seeds/*.sql; do
  base="$(basename "$f")"
  if ! grep -qF "seeds/${base}" "$MANIFEST"; then
    echo "ERROR: seeds/${base} exists on disk but is not listed in seed.manifest"
    missing=1
  fi
done
shopt -u nullglob

if [[ "$missing" -ne 0 ]]; then
  exit 1
fi

echo "Wrote ${OUT} ($(wc -l <"$OUT") lines)"
