import { spawn, spawnSync } from 'node:child_process'
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import { defineCommand } from 'citty'
import consola from 'consola'

import { c } from '@lenserfight/cli-client'

import { buildCliToolManifest } from '../lib/opencode-tool-bridge'

// `lf assist` (also the default when `lf`/`lenserfight` is run with no
// subcommand) — an interactive agent session pre-wired with every lf
// command as a tool, plus this project's MCP server config, when present.
// Built on the OpenCode runtime (https://github.com/anomalyco/opencode,
// MIT) — see NOTICE.md for attribution. See
// docs/en/tutorials/getting-started/cli-getting-started.md for details.

interface McpServerConfig {
  command: string
  args?: string[]
  env?: Record<string, string>
}

function cliBinaryPath(): string {
  return fileURLToPath(import.meta.url)
}

function findPluginBundle(): string | null {
  const candidates = [
    // Monorepo dist layout: dist/apps/cli/main.js -> dist/libs/adapters/opencode-plugin/
    resolve(dirname(cliBinaryPath()), '../../libs/adapters/opencode-plugin/lf-plugin.js'),
    // Nx workspace dev layout, resolved from cwd.
    resolve(process.cwd(), 'dist/libs/adapters/opencode-plugin/lf-plugin.js'),
  ]
  for (const candidate of candidates) {
    if (existsSync(candidate)) return candidate
  }
  return null
}

/** Translates this project's .mcp.json (Claude Code's format) into the runtime's `mcp` config shape. */
function readMcpConfig(projectDir: string): Record<string, unknown> | null {
  const mcpJsonPath = resolve(projectDir, '.mcp.json')
  if (!existsSync(mcpJsonPath)) return null

  try {
    const parsed = JSON.parse(readFileSync(mcpJsonPath, 'utf8')) as {
      mcpServers?: Record<string, McpServerConfig>
    }
    const servers = parsed.mcpServers ?? {}
    const mcp: Record<string, unknown> = {}
    for (const [name, server] of Object.entries(servers)) {
      mcp[name] = {
        type: 'local',
        command: [server.command, ...(server.args ?? [])],
      }
    }
    return Object.keys(mcp).length > 0 ? mcp : null
  } catch {
    return null
  }
}

function resolveAssistBinary(): { command: string; args: string[] } {
  const check = spawnSync('opencode', ['--version'], { stdio: 'ignore' })
  if (!check.error) return { command: 'opencode', args: [] }
  return { command: 'npx', args: ['--yes', 'opencode-ai'] }
}

export interface RunAssistOptions {
  force?: boolean
  passthroughArgs?: string[]
}

export async function runAssist(opts: RunAssistOptions = {}): Promise<void> {
  const pluginPath = findPluginBundle()
  if (!pluginPath) {
    consola.error(
      'Assist runtime not built yet. Build it first:\n' + '  pnpm nx run adapters-opencode:bundle-plugin',
    )
    process.exit(4)
  }

  const projectDir = process.cwd()
  const opencodeDir = resolve(projectDir, '.opencode')
  const configPath = resolve(opencodeDir, 'opencode.json')
  const manifestPath = resolve(opencodeDir, 'lf-cli-tools-manifest.json')

  if (existsSync(configPath) && !opts.force) {
    consola.error(`${configPath} already exists. Re-run with --force to regenerate it.`)
    process.exit(5)
  }

  mkdirSync(opencodeDir, { recursive: true })

  const tools = await buildCliToolManifest()
  writeFileSync(manifestPath, JSON.stringify({ cliBinaryPath: cliBinaryPath(), tools }, null, 2) + '\n')

  const mcp = readMcpConfig(projectDir)
  writeFileSync(
    configPath,
    JSON.stringify(
      {
        $schema: 'https://opencode.ai/config.json',
        plugin: [pluginPath],
        ...(mcp ? { mcp } : {}),
      },
      null,
      2,
    ) + '\n',
  )
  consola.info(
    `${c.brandGold('LenserFight')} assist ready — lens run, battle create, and ${tools.length} other lf ` +
      `command(s) available as tools${mcp ? ', mcp: ' + Object.keys(mcp).join(', ') : ''}. Destructive ` +
      'commands (kill-switch, dark-launch, db reset, etc) keep their existing --confirm gate — review ' +
      'what the agent does before trusting it.',
  )

  const { command, args: prefixArgs } = resolveAssistBinary()
  const child = spawn(command, [...prefixArgs, ...(opts.passthroughArgs ?? [])], {
    stdio: 'inherit',
    cwd: projectDir,
    env: { ...process.env, LF_OPENCODE_MANIFEST_PATH: manifestPath },
  })
  await new Promise<void>((resolvePromise) => {
    child.on('exit', (code) => {
      process.exitCode = code ?? 0
      resolvePromise()
    })
  })
}

export default defineCommand({
  meta: {
    name: 'assist',
    description: 'Launch an interactive agent session with every lf command available as a tool.',
  },
  args: {
    force: {
      type: 'boolean',
      default: false,
      description: 'Overwrite an existing .opencode/opencode.json generated by a previous run.',
    },
  },
  async run({ args, rawArgs }) {
    await runAssist({ force: Boolean(args.force), passthroughArgs: rawArgs.filter((a) => a !== '--force') })
  },
})
