import { spawn, spawnSync } from 'node:child_process'
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import { defineCommand } from 'citty'
import consola from 'consola'

// [experimental] `lf opencode` — spawns anomalyco/opencode
// (https://github.com/anomalyco/opencode) wired up with a LenserFight
// plugin (lf_lens_run, lf_battle_create — see libs/adapters/opencode) plus
// this project's existing MCP server config, when present. See
// docs/en/tutorials/getting-started/cli-getting-started.md and
// ~/.claude/plans/eventual-cooking-sparkle.md (Phase 2) for background.

interface McpServerConfig {
  command: string
  args?: string[]
  env?: Record<string, string>
}

function findPluginBundle(): string | null {
  const candidates = [
    // Monorepo dist layout: dist/apps/cli/main.js -> dist/libs/adapters/opencode-plugin/
    resolve(dirname(fileURLToPath(import.meta.url)), '../../libs/adapters/opencode-plugin/lf-plugin.js'),
    // Nx workspace dev layout, resolved from cwd.
    resolve(process.cwd(), 'dist/libs/adapters/opencode-plugin/lf-plugin.js'),
  ]
  for (const c of candidates) {
    if (existsSync(c)) return c
  }
  return null
}

/** Translates this project's .mcp.json (Claude Code's format) into OpenCode's `mcp` config shape. */
function readMcpConfig(projectDir: string): Record<string, unknown> | null {
  const mcpJsonPath = resolve(projectDir, '.mcp.json')
  if (!existsSync(mcpJsonPath)) return null

  try {
    const parsed = JSON.parse(readFileSync(mcpJsonPath, 'utf8')) as {
      mcpServers?: Record<string, McpServerConfig>
    }
    const servers = parsed.mcpServers ?? {}
    const mcp: Record<string, unknown> = {}
    for (const [name, server] of Object.entries(servers)) {
      mcp[name] = {
        type: 'local',
        command: [server.command, ...(server.args ?? [])],
      }
    }
    return Object.keys(mcp).length > 0 ? mcp : null
  } catch {
    return null
  }
}

function resolveOpencodeBinary(): { command: string; args: string[] } {
  const check = spawnSync('opencode', ['--version'], { stdio: 'ignore' })
  if (!check.error) return { command: 'opencode', args: [] }
  return { command: 'npx', args: ['--yes', 'opencode-ai'] }
}

export default defineCommand({
  meta: {
    name: 'opencode',
    hidden: true,
    description:
      '[experimental] Launch OpenCode (anomalyco/opencode) wired up with LenserFight tools and this project\'s MCP config.',
  },
  args: {
    force: {
      type: 'boolean',
      default: false,
      description: 'Overwrite an existing .opencode/opencode.json generated by a previous run.',
    },
  },
  async run({ args, rawArgs }) {
    consola.warn(
      '`lf opencode` is experimental. It spawns a separate opencode-ai process; see ' +
        'docs/en/tutorials/getting-started/cli-getting-started.md before relying on it.',
    )

    const pluginPath = findPluginBundle()
    if (!pluginPath) {
      consola.error(
        'OpenCode plugin bundle not found. Build it first:\n' +
          '  pnpm nx run adapters-opencode:bundle-plugin',
      )
      process.exit(4)
    }

    const projectDir = process.cwd()
    const opencodeDir = resolve(projectDir, '.opencode')
    const configPath = resolve(opencodeDir, 'opencode.json')

    if (existsSync(configPath) && !args.force) {
      consola.error(`${configPath} already exists. Re-run with --force to regenerate it.`)
      process.exit(5)
    }

    mkdirSync(opencodeDir, { recursive: true })
    const mcp = readMcpConfig(projectDir)
    writeFileSync(
      configPath,
      JSON.stringify(
        {
          $schema: 'https://opencode.ai/config.json',
          plugin: [pluginPath],
          ...(mcp ? { mcp } : {}),
        },
        null,
        2,
      ) + '\n',
    )
    consola.info(`Generated ${configPath} (lf_lens_run, lf_battle_create${mcp ? ', mcp: ' + Object.keys(mcp).join(', ') : ''})`)

    const { command, args: prefixArgs } = resolveOpencodeBinary()
    const passthroughArgs = rawArgs.filter((a) => a !== '--force')
    const child = spawn(command, [...prefixArgs, ...passthroughArgs], {
      stdio: 'inherit',
      cwd: projectDir,
    })
    child.on('exit', (code) => process.exit(code ?? 0))
  },
})
