import type { CatalogNodeEntry } from '../workflow-node-catalog'

export const TRIGGER_NODES: CatalogNodeEntry[] = [
  {
    type: 'manual_trigger',
    label: 'Manual Trigger',
    description: 'Start a workflow manually from the Studio or API.',
    category: 'trigger',
    color: 'text-rose-500',
    iconName: 'Play',
    inputs: [],
    outputs: [{ name: 'payload', type: 'json', description: 'User-supplied root inputs' }],
    requiredConfig: [],
    optionalConfig: ['inputSchema'],
    exampleConfig: { inputSchema: { topic: 'string', audience: 'string' } },
    acceptsInputTypes: ['void'],
    producesOutputType: 'json',
    n8nEquivalent: 'n8n-nodes-base.manualTrigger',
    docsPath: '/en/explanation/workflows/triggers',
  },
  {
    type: 'event_trigger',
    label: 'Event Trigger',
    description: 'Start a workflow when a platform event fires (battle completed, lens published, etc.).',
    category: 'trigger',
    color: 'text-rose-500',
    iconName: 'Bell',
    inputs: [],
    outputs: [{ name: 'event', type: 'json', description: 'Event payload with type and data' }],
    requiredConfig: ['eventType'],
    optionalConfig: ['filterExpression'],
    exampleConfig: { eventType: 'battle.completed', filterExpression: 'event.data.winner_id === ctx.lenserId' },
    acceptsInputTypes: ['void'],
    producesOutputType: 'json',
    n8nEquivalent: 'n8n-nodes-base.webhook',
    docsPath: '/en/explanation/workflows/triggers',
  },
  {
    type: 'form_input_trigger',
    label: 'Form / Input Trigger',
    description: 'Start a workflow from a user-submitted form with validated fields.',
    category: 'trigger',
    color: 'text-rose-500',
    iconName: 'FormInput',
    inputs: [],
    outputs: [{ name: 'formData', type: 'json', description: 'Validated form field values' }],
    requiredConfig: ['fields'],
    optionalConfig: ['title', 'description', 'submitLabel'],
    exampleConfig: {
      fields: [
        { name: 'prompt', type: 'text', required: true, label: 'Your question' },
        { name: 'context', type: 'textarea', required: false, label: 'Additional context' },
      ],
      title: 'Ask AI',
      submitLabel: 'Run Workflow',
    },
    acceptsInputTypes: ['void'],
    producesOutputType: 'json',
    n8nEquivalent: 'n8n-nodes-base.formTrigger',
    docsPath: '/en/explanation/workflows/triggers',
  },
]
